/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#bbcabf',
        'inverse-surface': '#dfe2ee',
        'inverse-on-surface': '#2c3039',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
        'surface-tint': '#4edea3',
        'surface-variant': '#31353e',
        'background': '#0f131c',
        'on-background': '#dfe2ee',
        'primary': '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'secondary': '#7bd0ff',
        'on-secondary': '#00354a',
        'secondary-container': '#00a6e0',
        'on-secondary-container': '#00374d',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'tertiary': '#ffb95f',
        'on-tertiary': '#472a00',
        'tertiary-container': '#e29100',
        'on-tertiary-container': '#523200',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-3xs': '0.125rem',
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-desktop': '1rem',
        'margin-desktop': '1.5rem',
        'gutter-mobile': '0.75rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        headline: ['Chivo', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'label-data': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Chivo', 'sans-serif'],
        'headline-xl-mobile': ['Chivo', 'sans-serif'],
        'metric-mono-lg': ['JetBrains Mono', 'monospace'],
        'headline-2xl-mobile': ['Chivo', 'sans-serif'],
        'headline-lg': ['Chivo', 'sans-serif'],
        'headline-2xl': ['Chivo', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Chivo', 'sans-serif'],
        'metric-mono-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Chivo', 'sans-serif'],
      },
      fontSize: {
        'label-data': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-xl-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'metric-mono-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-2xl-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-2xl': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '42px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'metric-mono-md': ['15px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}