export const IMPORT_SCHEMAS = {
  players: {
    entity: 'players',
    title: 'Players & Roster',
    apiEndpoint: '/players/bulk-import',
    fields: [
      { key: 'first_name', label: 'First Name', aliases: ['firstname', 'first', 'given_name', 'player_first_name'], type: 'string' },
      { key: 'last_name', label: 'Last Name', aliases: ['lastname', 'last', 'family_name', 'surname', 'player_last_name'], type: 'string' },
      { key: 'dob', label: 'Birth Date (DOB)', aliases: ['date_of_birth', 'birth_date', 'birthday', 'dob_date'], type: 'string' },
      { key: 'nationality', label: 'Nationality', aliases: ['country', 'nation', 'citizenship'], type: 'string' },
      { key: 'position', label: 'Position', aliases: ['pos', 'role', 'playing_position'], type: 'string' },
      { key: 'height_cm', label: 'Height (cm)', aliases: ['height', 'height_in_cm', 'stature'], type: 'integer' },
      { key: 'preferred_foot', label: 'Preferred Foot', aliases: ['foot', 'dominant_foot'], type: 'string', default: 'Right' },
      { key: 'market_value_m', label: 'Market Value (M EUR)', aliases: ['market_value', 'value', 'valuation', 'market_value_eur_millions', 'market_value_eur', 'market_value_m_eur', 'value_m', 'market_val'], type: 'float', default: 0 },
      { key: 'jersey_number', label: 'Jersey Number', aliases: ['jersey', 'number', 'kit_number', 'shirt_number', 'kit_no'], type: 'integer' },
      { key: 'team_id', label: 'Team ID', aliases: ['team', 'national_team_id', 'assigned_team', 'national_team', 'squad', 'team_name'], type: 'string' },
      { key: 'club', label: 'Club Team', aliases: ['current_club', 'parent_club', 'club_team'], type: 'string' },
    ],
  },
  teams: {
    entity: 'teams',
    title: 'National & Club Teams',
    apiEndpoint: '/teams/bulk-import',
    fields: [
      { key: 'name', label: 'Team Name', aliases: ['team_name', 'nation', 'country'], type: 'string' },
      { key: 'nickname', label: 'Nickname', aliases: ['alias', 'aka', 'team_nickname'], type: 'string' },
      { key: 'foundation_year', label: 'Foundation Year', aliases: ['year_founded', 'founded', 'year'], type: 'integer' },
      { key: 'jersey_color', label: 'Jersey Color', aliases: ['kit_color', 'primary_color', 'colors'], type: 'string' },
      { key: 'fifa_ranking', label: 'FIFA Ranking', aliases: ['ranking', 'rank', 'world_rank'], type: 'integer' },
      { key: 'association_id', label: 'Association ID', aliases: ['confederation_id', 'assoc_id'], type: 'integer' },
    ],
  },
  coaches: {
    entity: 'coaches',
    title: 'Coaching Staff',
    apiEndpoint: '/coaches/bulk-import',
    fields: [
      { key: 'first_name', label: 'First Name', aliases: ['firstname', 'first'], type: 'string' },
      { key: 'last_name', label: 'Last Name', aliases: ['lastname', 'last', 'surname'], type: 'string' },
      { key: 'dob', label: 'Birth Date (DOB)', aliases: ['date_of_birth', 'birth_date'], type: 'string' },
      { key: 'nationality', label: 'Nationality', aliases: ['country', 'nation'], type: 'string' },
      { key: 'license_no', label: 'License No', aliases: ['license', 'license_number', 'coaching_badge'], type: 'string' },
      { key: 'start_date', label: 'Start Date', aliases: ['appointed_date', 'contract_start', 'since'], type: 'string' },
      { key: 'end_date', label: 'End Date', aliases: ['contract_end', 'until'], type: 'string' },
      { key: 'team_id', label: 'Team ID', aliases: ['team', 'assigned_team_id'], type: 'integer' },
    ],
  },
  referees: {
    entity: 'referees',
    title: 'Match Officials & Referees',
    apiEndpoint: '/referees/bulk-import',
    fields: [
      { key: 'first_name', label: 'First Name', aliases: ['firstname', 'first'], type: 'string' },
      { key: 'last_name', label: 'Last Name', aliases: ['lastname', 'last', 'surname'], type: 'string' },
      { key: 'nationality', label: 'Nationality', aliases: ['country', 'nation'], type: 'string' },
      { key: 'badge_no', label: 'Badge No', aliases: ['badge', 'badge_number', 'fifa_badge'], type: 'string' },
      { key: 'role', label: 'Role / Level', aliases: ['designation', 'referee_role', 'category'], type: 'string', default: 'Main Referee' },
    ],
  },
  stadiums: {
    entity: 'stadiums',
    title: 'Venues & Stadiums',
    apiEndpoint: '/stadiums/bulk-import',
    fields: [
      { key: 'name', label: 'Stadium Name', aliases: ['stadium_name', 'venue', 'arena'], type: 'string' },
      { key: 'capacity', label: 'Capacity', aliases: ['seats', 'total_capacity', 'max_capacity'], type: 'integer' },
      { key: 'location', label: 'Location / Address', aliases: ['address', 'street', 'area'], type: 'string' },
      { key: 'city', label: 'City', aliases: ['town', 'metro'], type: 'string' },
      { key: 'country', label: 'Country', aliases: ['nation', 'state'], type: 'string' },
    ],
  },
  tournaments: {
    entity: 'tournaments',
    title: 'Tournaments & Cups',
    apiEndpoint: '/tournaments/bulk-import',
    fields: [
      { key: 'name', label: 'Tournament Name', aliases: ['tournament_name', 'competition', 'title'], type: 'string' },
      { key: 'type', label: 'Type', aliases: ['tournament_type', 'category'], type: 'string', default: 'International' },
      { key: 'format', label: 'Format', aliases: ['structure', 'tournament_format'], type: 'string', default: 'Knockout' },
      { key: 'start_date', label: 'Start Date', aliases: ['starts', 'from_date'], type: 'string' },
      { key: 'end_date', label: 'End Date', aliases: ['ends', 'to_date'], type: 'string' },
    ],
  },
  associations: {
    entity: 'associations',
    title: 'Member Associations & Confederations',
    apiEndpoint: '/associations/bulk-import',
    fields: [
      { key: 'name', label: 'Association Name', aliases: ['association_name', 'confederation', 'org_name'], type: 'string' },
      { key: 'region', label: 'Region / Continent', aliases: ['continent', 'zone', 'territory'], type: 'string' },
      { key: 'fifa_code', label: 'FIFA Code', aliases: ['code', 'abbreviation', 'ioc_code'], type: 'string' },
      { key: 'foundation_date', label: 'Foundation Date', aliases: ['founded', 'established', 'foundation_year'], type: 'string' },
    ],
  },
  sponsors: {
    entity: 'sponsors',
    title: 'Global Partners & Sponsors',
    apiEndpoint: '/sponsors/bulk-import',
    fields: [
      { key: 'name', label: 'Sponsor Name', aliases: ['company', 'brand', 'partner_name'], type: 'string' },
      { key: 'industry', label: 'Industry', aliases: ['sector', 'category', 'market_sector'], type: 'string' },
      { key: 'country', label: 'Country', aliases: ['headquarters', 'hq_country', 'nation'], type: 'string' },
    ],
  },
  matches: {
    entity: 'matches',
    title: 'Matches & Fixtures',
    apiEndpoint: '/matches/bulk-import',
    fields: [
      { key: 'tournament_id', label: 'Tournament ID', aliases: ['tournament'], type: 'integer' },
      { key: 'stadium_id', label: 'Stadium ID', aliases: ['stadium', 'venue_id'], type: 'integer' },
      { key: 'home_team_id', label: 'Home Team ID', aliases: ['home_team', 'home_id'], type: 'integer' },
      { key: 'away_team_id', label: 'Away Team ID', aliases: ['away_team', 'away_id'], type: 'integer' },
      { key: 'match_date', label: 'Match Date', aliases: ['date'], type: 'string' },
      { key: 'match_time', label: 'Match Time', aliases: ['time', 'kickoff'], type: 'string', default: '20:00:00' },
      { key: 'stage', label: 'Stage', aliases: ['round', 'phase'], type: 'string', default: 'Group Stage' },
      { key: 'result', label: 'Result', aliases: ['score', 'final_score'], type: 'string' },
    ],
  },
};
